apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::991582104158:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::991582104158:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5NUPAP3RV9L9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-31T15:48:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "38078"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 187cf68f-8e49-41b3-9450-545f42cfcf6d
